const enum AppCssClass {
  LOGO = 'logo',
  HEADER = 'header',
  WRAPPER = 'wrapper',
  HEADER_BTN = 'header__btn',
  HEADER_BUTTONS = 'header__buttons',
  FIRST_VIEW = 'first-view',
  ACC_MENU = 'acc-menu',
  ACC_MENU_VISIBLE = 'acc-menu_visible',
  ACC_MENU_HIDDEN = 'acc-menu_hidden',
  ACC_MENU_NAME = 'acc-menu__login-name',
  ACC_MENU_BTN = 'acc-menu__button',

  PAGE_HEADING = 'page-heading',

  FIRST_VIEW_LOGO = 'first-view__logo',
  FIRST_VIEW_BUTTONS = 'fist-view__buttons',
  BUTTON_DIV_IMG = 'button-div__img',
  BUTTON_DISABLED = 'button-div__disabled',
  BUTTON_DIV_IMG_LEFT = 'button-div__img_left',
  BUTTON_DIV_IMG_RIGHT = 'button-div__img_right',
  BUTTON_DIV = 'first-view__button-div',
  BUTTON = 'button',
  BUTTON_BIG = 'button_big',
  BUTTON_BLUE = 'button_blue',


  PREGAME = 'pregame',
  BOARD_CONTAINER = 'pregame__board-container',
  BOARD_CONTAINER_TEXT = 'pregame__board-text',
  CONTROL_CONTAINER = 'pregame__control-container',
  CONTROL_HEADER = 'pregame__header',
  DIFFICULT_CONTAINER = "pregame__difficult-container",
  DIFFICULT = 'pregame__difficult',
  DIFFICULT_ACTIVE = 'pregame__difficult_active',
  DIFFICULT_HEADER = 'pregame__difficult-header',
  DIFFICULT_FEATURES = 'pregame__difficult-features',

  LOAD_BLOCK = "load-block",
  LOAD_BLOCK_CONTAINER = "load-block__container",
  LOAD_BLOCK_IMG = "load-block__img",
  LOAD_BLOCK_TITLE = "load-block__title",

  BOARD_MARKUP = 'board__markup',
  BOARD_MARKUP_EASY = 'board__markup_easy',
  BOARD_EMPTY_BLOCK = 'board__empty-block',
  EMPTY_CONTAINER = 'empty-container',
  BOARD = 'board',
  DARK_BLOCK = 'dark-block',
  BOARD_EASY = 'board_easy',
  BOARD_IMG = 'board_img',
  HIT_IMG = 'hit_img',
  MISS_IMG = 'miss_img',
  EMPTY_IMG = 'empty_img',

  SHIP = 'ship',
  PLACING_ERROR = 'placing-error',
  ANIMATION_ERROR = 'animation-error',
  SHIP_DRAG_LOCK = 'ship_locked',

  GAME = 'game',
  GAME_CONTAINER = 'game__container',
  GAME_BOARD_NAME = 'game__board-name',
  GAME_SHIP = 'game__ship',
  MARKED_SHIP = 'game__ship_marked',
  GAME_SQUADRON = 'game__squadron',
  GAME_SQUADRON_ROW = 'game__squadron-row',
  GAME_SQUADRON_ROW_RIGHT = 'game__squadron-row_right',
  GAME_STATS = 'game-stats',
  GAME_STATS_TIMER = 'game-stats__timer',
  GAME_STATS_ANONS = 'game-stats__anons',
  GAME_STATS_TURNS_COUNT = 'game-stats__turns-count',

  NOSHIP_CELL = 'noship-cell',
  MISS_CELL = 'miss-cell',
  HIT_CELL = 'hit-cell',

  WIN = 'win',
  WIN_TITLE = 'win__title',
  WIN_TEXT = 'win__text',
  WIN_TEXT_LOSE = 'win__text_lose',
  WIN_POSITION = 'win__position',
  WIN_HOME = 'win__home',

  REGISTRATION = 'registration',
  REGISTRATION_FORM = "registration__form",
  FORM = "form",
  FORM_INPUT_BLOCK = 'form__input-block',
  FORM_LABEL = "form__label",
  FORM_INPUT = 'form__input',
  IMAGE_LABEL = 'image-label',
  FORM_FILE_BTN = 'form__file-btn',
  FORM_SUBMIT_BTN = 'form__submit-btn',
  FORM_SPAN = 'form__span',
  HIDDEN = 'hidden'
}

export default AppCssClass;
